version: "3"
services: 
  db:
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: Magomed
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: learnbd
    restart: always


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080